import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  outerSafeArea: {
    flex: 1,
    backgroundColor: '#F4F9F4',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#FAFDF9',
    alignItems: 'center',
    width: '100%',
  },
  mobileCanvas: {
    width: '100%',
    maxWidth: 480,
    flex: 1,
    backgroundColor: '#FAFDF9',
    position: 'relative',
  },
  scrollContent: {
    paddingBottom: 70,
  },
  topHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  locationSelector: {
    flexDirection: 'column',
  },
  locationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationHomeText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#123C24',
    marginLeft: 6,
    marginRight: 2,
  },
  locationAddressText: {
    fontSize: 12.5,
    fontWeight: '400',
    color: '#5A655D',
    marginTop: 2,
  },
  rightActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
  },
  cartBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#1B753A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  searchSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  searchBarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    height: 48,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E6ECE6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    marginRight: 6,
    fontSize: 13,
    color: '#1F2937',
    outlineStyle: 'none',
  },
  heroBannerCard: {
    marginHorizontal: 6,
    marginBottom: 20,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#EAF5E9',
    aspectRatio: 1320 / 600,
    shadowColor: '#1B753A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  heroBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  categoriesSection: {
    marginBottom: 16,
  },
  categoriesScrollContent: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  categoryItem: {
    alignItems: 'center',
    marginRight: 12,
    width: 72,
  },
  categoryIconImage: {
    width: 66,
    height: 66,
    borderRadius: 16,
  },
  categoryLabelText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#123C24',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 14,
  },

  /* BANNER 2 (10-MINUTE PROMO BANNER) STYLES FOR BANNER21.PNG */
  banner2Container: {
    marginHorizontal: 6,
    marginBottom: 20,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 2051 / 463,
    backgroundColor: '#FFF0F3',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  banner2Image: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  banner2OverlayContent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  banner2TextCol: {
    flexDirection: 'column',
    justifyContent: 'center',
    maxWidth: '55%',
  },
  banner2Subhead: {
    fontSize: 10,
    fontWeight: '600',
    color: '#DC2626',
    letterSpacing: -0.2,
  },
  banner2Headline: {
    fontSize: 17.5,
    fontWeight: '800',
    color: '#B91C1C',
    marginVertical: 0.5,
    letterSpacing: -0.5,
  },
  banner2Tagline: {
    fontSize: 9,
    fontWeight: '500',
    color: '#991B1B',
  },
  banner2OrderBtn: {
    position: 'absolute',
    right: 6,
    top: '55%',
    transform: [{ translateY: 0 }],
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 7,
    paddingHorizontal: 5.5,
    paddingTop: 3.5,
    paddingBottom: 2.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  banner2OrderBtnText: {
    fontSize: 7.2,
    fontWeight: '700',
    color: '#B91C1C',
    letterSpacing: -0.1,
  },

  /* FRESH PICKS FOR YOU SECTION STYLES (4 CARDS FULLY VISIBLE AT 320PX) */
  freshPicksSection: {
    marginBottom: 6,
    marginTop: 2,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  sectionTitleText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  seeAllText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#16A34A',
  },

  /* WHAT OUR CUSTOMERS SAY SECTION STYLES */
  reviewsRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    paddingHorizontal: 6,
    width: '100%',
    marginBottom: 4,
  },
  reviewCard: {
    flex: 1,
    maxWidth: '32%',
    backgroundColor: '#F4FAF5',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E4F2E6',
    paddingHorizontal: 7,
    paddingVertical: 10,
    marginHorizontal: 1.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  reviewTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewAvatarImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 5,
  },
  reviewAuthorCol: {
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 1,
  },
  reviewAuthorName: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#0F172A',
    lineHeight: 13,
  },
  reviewStarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  reviewQuoteText: {
    fontSize: 9.2,
    fontWeight: '500',
    color: '#334155',
    lineHeight: 13,
    marginTop: 3,
  },

  productsRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    paddingHorizontal: 8,
    width: '100%',
  },
  productCard: {
    flex: 1,
    maxWidth: '23.8%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    paddingHorizontal: 3,
    paddingVertical: 4,
    marginHorizontal: 1,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1.5,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  discountBadge: {
    position: 'absolute',
    top: 3,
    left: 3,
    backgroundColor: '#16A34A',
    borderRadius: 4,
    paddingHorizontal: 2.5,
    paddingVertical: 0.5,
    zIndex: 2,
  },
  discountBadgeText: {
    fontSize: 6,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -0.1,
  },
  productImage: {
    width: '100%',
    height: 38,
    marginTop: 2,
    marginBottom: 2,
  },
  productTitleText: {
    fontSize: 8.5,
    fontWeight: '700',
    color: '#1E293B',
    lineHeight: 10,
  },
  productWeightText: {
    fontSize: 7,
    fontWeight: '400',
    color: '#94A3B8',
    marginTop: 1,
  },
  productPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  currentPriceText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#0F172A',
  },
  originalPriceText: {
    fontSize: 6.5,
    fontWeight: '400',
    color: '#94A3B8',
    textDecorationLine: 'line-through',
    marginLeft: 1,
  },
  addBtn: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1.5,
  },

  /* OFFERS FOR YOU SECTION STYLES */
  offersSection: {
    marginBottom: 8,
    marginTop: 4,
  },
  offersScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 4,
  },
  offerCard: {
    width: 114,
    height: 104,
    borderRadius: 14,
    padding: 8,
    marginRight: 10,
    flexDirection: 'column',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1.5,
  },
  offerCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  offerTitleText: {
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
    letterSpacing: -0.2,
    flex: 1,
    marginRight: 4,
  },
  offerCircleArrow: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  offerCardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  offerSubtext: {
    fontSize: 9,
    fontWeight: '800',
    lineHeight: 11,
    letterSpacing: -0.1,
    marginBottom: 2,
  },
  offerArtworkImage: {
    width: 48,
    height: 48,
  },

  /* FIXED BOTTOM NAVIGATION BAR STYLES */
  fixedBottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 56,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
  },
  navTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  navTabActiveLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#16A34A',
    marginTop: 2,
  },
  navTabLabel: {
    fontSize: 10.5,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  navIconContainer: {
    position: 'relative',
  },
  offersRedBadge: {
    position: 'absolute',
    top: -2,
    right: -3,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#EF4444',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },

  /* KITCHEN ESSENTIALS PROMO BANNER STYLES */
  kitchenBannerContainer: {
    marginHorizontal: 6,
    marginTop: 4,
    marginBottom: 20,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 540 / 167,
    backgroundColor: '#E6F4EA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  kitchenBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },

  /* JOIN OUR MEMBERSHIP PROMO BANNER STYLES */
  membershipBannerContainer: {
    marginHorizontal: 6,
    marginTop: 4,
    marginBottom: 6,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 1362 / 460,
    backgroundColor: '#FFFDF5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  membershipBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },

  /* FESTIVAL ESSENTIALS PROMO BANNER STYLES */
  festivalBannerContainer: {
    marginHorizontal: 6,
    marginTop: 0,
    marginBottom: 6,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 1334 / 340,
    backgroundColor: '#FDF2F4',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  festivalBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },

  /* READ & LEARN SECTION STYLES */
  readRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 6,
    marginBottom: 8,
  },
  readCardItem: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  readCardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  greenerBannerContainer: {
    marginHorizontal: 6,
    marginBottom: 6,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 1974 / 430,
    backgroundColor: '#E8F5EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  greenerBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },

  /* WHY SHOP WITH US NO-BOX SECTION STYLES */
  whyShopNoBoxContainer: {
    marginHorizontal: 8,
    marginTop: 8,
    marginBottom: 6,
    aspectRatio: 2031 / 573,
    backgroundColor: 'transparent',
  },
  whyShopNoBoxImage: {
    width: '100%',
    height: '100%',
  },

  /* FRESH CHOICES PROMO BANNER STYLES */
  freshChoicesBannerContainer: {
    marginHorizontal: 6,
    marginTop: 0,
    marginBottom: 10,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 1600 / 520,
    backgroundColor: '#EBF7ED',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  freshChoicesBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },

  /* STAY UPDATED NEWSLETTER BANNER STYLES */
  stayUpdatedBannerContainer: {
    marginHorizontal: 6,
    marginTop: 0,
    marginBottom: 24,
    borderRadius: 16,
    overflow: 'hidden',
    aspectRatio: 1600 / 520,
    backgroundColor: '#EBF7ED',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  stayUpdatedBannerImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
});
